name: web_view_flutter
description: A Flutter project to wrap driver.zoonasd.com

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # أحدث نسخة WebView مدعومة
  webview_flutter: ^4.7.0

  # OneSignal Flutter
  onesignal_flutter: ^5.0.4

  # Cupertino icons
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true